name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  resume-build:
    name: JSON Resume Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Generate pdf
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-stackoverflow
          resume export resume.pdf --theme=stackoverflow
          resume export resume.html --theme=stackoverflow
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-resume
          path: |
            resume.pdf
            resume.html